<?xml version="1.0" encoding="utf-8"?>
<Project>
    <PropertyGroup>
        <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
    </PropertyGroup>
    <ItemGroup>
        <PackageVersion Include="Testcontainers" Version="4.15.0"/>
        <!-- Unit and integration test dependencies: -->
        <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="18.9.0"/>
        <PackageVersion Include="coverlet.collector" Version="10.0.1"/>
        <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.5"/>
        <PackageVersion Include="xunit.v3" Version="3.2.2"/>
        <!-- Third-party client dependencies to connect and interact with the containers: -->
        <PackageVersion Include="ChromaDotNet.Client" Version="2.7.0"/>
    </ItemGroup>
</Project>
